/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/0_Calculus_LinearAlgebra': RouteRecordInfo<'/posts/0_Calculus_LinearAlgebra', '/posts/0_Calculus_LinearAlgebra', Record<never, never>, Record<never, never>>,
    '/posts/1_1_Machine_Learning_Types': RouteRecordInfo<'/posts/1_1_Machine_Learning_Types', '/posts/1_1_Machine_Learning_Types', Record<never, never>, Record<never, never>>,
    '/posts/1_2_Linear_Regression': RouteRecordInfo<'/posts/1_2_Linear_Regression', '/posts/1_2_Linear_Regression', Record<never, never>, Record<never, never>>,
    '/posts/1_3_Logistic_Regression': RouteRecordInfo<'/posts/1_3_Logistic_Regression', '/posts/1_3_Logistic_Regression', Record<never, never>, Record<never, never>>,
    '/posts/1_4_Generalized_Linear_Models': RouteRecordInfo<'/posts/1_4_Generalized_Linear_Models', '/posts/1_4_Generalized_Linear_Models', Record<never, never>, Record<never, never>>,
    '/posts/2_1_Neural_Networks': RouteRecordInfo<'/posts/2_1_Neural_Networks', '/posts/2_1_Neural_Networks', Record<never, never>, Record<never, never>>,
    '/posts/Baby_Number_Theory': RouteRecordInfo<'/posts/Baby_Number_Theory', '/posts/Baby_Number_Theory', Record<never, never>, Record<never, never>>,
    '/posts/Backpack_DP': RouteRecordInfo<'/posts/Backpack_DP', '/posts/Backpack_DP', Record<never, never>, Record<never, never>>,
    '/posts/diff': RouteRecordInfo<'/posts/diff', '/posts/diff', Record<never, never>, Record<never, never>>,
    '/posts/Dijkstra_Proof': RouteRecordInfo<'/posts/Dijkstra_Proof', '/posts/Dijkstra_Proof', Record<never, never>, Record<never, never>>,
    '/posts/Finite-Dimensional_Vector_Space_LADR_Chapter_2': RouteRecordInfo<'/posts/Finite-Dimensional_Vector_Space_LADR_Chapter_2', '/posts/Finite-Dimensional_Vector_Space_LADR_Chapter_2', Record<never, never>, Record<never, never>>,
    '/posts/GSLA_Chapter_1': RouteRecordInfo<'/posts/GSLA_Chapter_1', '/posts/GSLA_Chapter_1', Record<never, never>, Record<never, never>>,
    '/posts/GSLA_Chapter_2': RouteRecordInfo<'/posts/GSLA_Chapter_2', '/posts/GSLA_Chapter_2', Record<never, never>, Record<never, never>>,
    '/posts/Magic_Bits_Operation': RouteRecordInfo<'/posts/Magic_Bits_Operation', '/posts/Magic_Bits_Operation', Record<never, never>, Record<never, never>>,
    '/posts/MultiLazyTag': RouteRecordInfo<'/posts/MultiLazyTag', '/posts/MultiLazyTag', Record<never, never>, Record<never, never>>,
    '/posts/Multiplication': RouteRecordInfo<'/posts/Multiplication', '/posts/Multiplication', Record<never, never>, Record<never, never>>,
    '/posts/Vector_Space_LADR_Chapter_1': RouteRecordInfo<'/posts/Vector_Space_LADR_Chapter_1', '/posts/Vector_Space_LADR_Chapter_1', Record<never, never>, Record<never, never>>,
    '/posts/XSCTF2024_PreRound_shy_vector_WriteUp': RouteRecordInfo<'/posts/XSCTF2024_PreRound_shy_vector_WriteUp', '/posts/XSCTF2024_PreRound_shy_vector_WriteUp', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
